/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Scala application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the scala Plugin to add support for Scala.
    scala

    // Apply the application plugin to add support for building a CLI application in Java.
    application
    
    // Apply the shadow plugin to build fat jars
    id("com.gradleup.shadow") version "8.3.11"
}

version = "1.0.0"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

val osName = System.getProperty("os.name").lowercase()
val osArch = System.getProperty("os.arch").lowercase()
val javaFxPlatform = when {
    osName.contains("win") -> "win"
    osName.contains("mac") -> if (osArch == "aarch64" || osArch == "arm64") "mac-aarch64" else "mac"
    osName.contains("linux") -> if (osArch == "aarch64" || osArch == "arm64") "linux-aarch64" else "linux"
    else -> "mac"
}

val targetArch = project.findProperty("targetArch")?.toString() ?: "local"
val targetPlatforms = when (targetArch) {
    "amd64" -> listOf("win", "mac", "linux")
    "aarch64" -> listOf("mac-aarch64", "linux-aarch64")
    else -> listOf(javaFxPlatform)
}

dependencies {
    // Use Scala 3 library
    implementation(libs.scala.library)

    // Protocols (Protobuf / ScalaPB schemas)
    implementation(project(":protocols"))
    implementation(libs.scalapb.runtime)

    // Kafka client for distributed telemetry
    implementation(libs.kafka.clients) {
        exclude(group = "org.lz4", module = "lz4-java")
    }

    // Cats for functional programming constructs
    implementation(libs.cats.core)
    implementation(libs.cats.effect)
    implementation(libs.fs2.core)

    // Pekko for the distributed actor model
    implementation(libs.pekko.actor.typed)
    implementation(libs.pekko.cluster.typed)
    implementation(libs.pekko.cluster.sharding.typed)
    implementation(libs.pekko.serialization.jackson)
    implementation(libs.pekko.persistence.typed)
    testImplementation(libs.pekko.actor.testkit.typed)
    testImplementation(libs.pekko.persistence.testkit)

    // ScalaFX for GUI components
    implementation(libs.scalafx)
    targetPlatforms.forEach { platform ->
        implementation(variantOf(libs.javafx.base) { classifier(platform) })
        implementation(variantOf(libs.javafx.graphics) { classifier(platform) })
        implementation(variantOf(libs.javafx.controls) { classifier(platform) })
        implementation(variantOf(libs.javafx.media) { classifier(platform) })
        implementation(variantOf(libs.javafx.web) { classifier(platform) })
        implementation(variantOf(libs.javafx.swing) { classifier(platform) })
    }

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(libs.smartgraph)

    // Use Scalatest for testing our library
    testImplementation(libs.junit)
    testImplementation(libs.scalatest)
    testImplementation(libs.junit.v4.v13.v2.v13)

    // Need scala-xml at test runtime
    testRuntimeOnly(libs.scala.xml)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.gridsim.gui.app.Launcher"
}

tasks.jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named<Jar>("shadowJar") {
    val suffix = if (targetArch == "local") "" else "-$targetArch"
    archiveFileName.set("${rootProject.name}${suffix}.jar")
}

tasks.register("ciAssemble") {
    group = "build"
    description = "CI assemble"
    dependsOn("assemble")
}

tasks.register("ciBuild") {
    group = "build"
    description = "CI build without added checks"
    dependsOn("assemble", "test")
}

tasks.register<JavaExec>("runGraphView") {
    group = "application"
    description = "Run the standalone Graph View test application"
    mainClass = "org.gridsim.gui.app.GraphViewApp"
    classpath = sourceSets["main"].runtimeClasspath
}

val gradlew = if (osName.contains("win")) "${rootProject.projectDir}\\gradlew.bat" else "${rootProject.projectDir}/gradlew"

tasks.register<Exec>("buildAmd64Jar") {
    group = "build"
    description = "Build a fat jar for all amd64 platforms (Windows, Linux, Mac Intel)"
    workingDir = rootProject.projectDir
    commandLine(gradlew, ":app:shadowJar", "-PtargetArch=amd64")
}

tasks.register<Exec>("buildAarch64Jar") {
    group = "build"
    description = "Build a fat jar for all aarch64 platforms (Mac Apple Silicon, Linux ARM)"
    workingDir = rootProject.projectDir
    commandLine(gradlew, ":app:shadowJar", "-PtargetArch=aarch64")
}

tasks.register("buildAllJars") {
    group = "build"
    description = "Build fat jars for both amd64 and aarch64 platforms"
    dependsOn("buildAmd64Jar", "buildAarch64Jar")
}
